#!/bin/bash
# RFC 6793 (BGP Support for Four-Octet AS Number Space) End-to-End Test
#
# Topology:
#   [gobgp-new (AS 4200000000)] --eBGP(AS4)--> [rusty (AS 65010)] --eBGP(bird-old: enable as4 off)--> [bird-old (AS 65020)] --eBGP(AS4)--> [frr-new (AS 4200000001)]
#            gobgp-net 172.30.40.0/24              bird-net 172.30.41.0/24                   frr-net 172.30.42.0/24
#
# bird-old is a real BIRD 2.19.1 build (tests/e2e/shared/Dockerfile.bird) configured
# with `enable as4 off;` toward rusty: it never advertises the Four-Octet AS Number
# capability on that session, making it a genuine RFC 6793 OLD BGP speaker.
#
# Test scenarios:
#   1. All three eBGP sessions establish -- notably rusty <-> bird-old, which lacks
#      the Four-Octet AS Number capability and must NOT be refused (RFC 6793 SS4.1;
#      pre-fix RustyBGP sent OpenUnsupportedCapability here instead of falling back).
#   2. ENCODE direction: rusty relays gobgp-new's wide-AS route (10.0.1.0/24,
#      AS_PATH originates as 4200000000) to bird-old over the two-octet session.
#      rusty must downgrade AS_PATH to two-octet + AS_TRANS and attach AS4_PATH
#      (RFC 6793 SS4.2.2); bird-old, a real independent implementation, must
#      reconstruct the correct AS_PATH "65010 4200000000" from it.
#   3. ENCODE direction, no-AS4_PATH case: rusty's own locally-originated route
#      (10.0.3.0/24, AS_PATH stays within 65010 only) must NOT carry an AS4_PATH
#      attribute -- verified indirectly via bird-old showing a clean AS_PATH.
#   4. DECODE direction: bird-old relays frr-new's wide-AS route (10.0.2.0/24,
#      AS_PATH originates as 4200000001) to rusty over the same two-octet session.
#      bird-old (not RustyBGP) performs the AS_PATH downgrade + AS4_PATH this time;
#      rusty must reconcile the real AS4_PATH generated by BIRD back into
#      AS_PATH "65020 4200000001" (RFC 6793 SS4.2.3).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"
source ../shared/helpers.sh

PASS=0
FAIL=0

pass() {
    echo "  PASS: $1"
    PASS=$((PASS + 1))
}

fail() {
    echo "  FAIL: $1"
    FAIL=$((FAIL + 1))
}

cleanup() {
    echo ""
    echo "Cleaning up..."
    docker compose down --volumes --remove-orphans 2>/dev/null || true
}
trap cleanup EXIT

echo "=== RFC 6793 Two-Octet AS Number Peer End-to-End Test ==="
echo ""

echo "Building and starting containers..."
docker compose up -d --build --force-recreate 2>&1

echo "Waiting for BGP convergence..."
MAX_WAIT=90
GOBGP_OK=false
BIRD_OK=false
FRR_OK=false

for i in $(seq 1 $MAX_WAIT); do
    if ! $GOBGP_OK && [ "$(gobgp_bgp_state gobgp-new 172.30.40.1)" = "Established" ]; then
        GOBGP_OK=true
        echo "  gobgp-new <-> rusty established after ${i}s"
    fi
    if ! $BIRD_OK && [ "$(bird_bgp_state bird-old to_rusty)" = "Established" ]; then
        BIRD_OK=true
        echo "  rusty <-> bird-old established after ${i}s"
    fi
    if ! $FRR_OK && [ "$(frr_bgp_state frr-new 172.30.42.1)" = "Established" ]; then
        FRR_OK=true
        echo "  bird-old <-> frr-new established after ${i}s"
    fi
    if $GOBGP_OK && $BIRD_OK && $FRR_OK; then
        break
    fi
    if [ "$i" -eq "$MAX_WAIT" ]; then
        echo "BGP sessions did not fully establish within ${MAX_WAIT}s"
        echo ""
        echo "--- gobgp-new neighbor ---"
        docker exec gobgp-new gobgp neighbor 2>/dev/null || true
        echo "--- bird-old protocols ---"
        docker exec bird-old birdc show protocols 2>/dev/null || true
        echo "--- frr-new bgp summary ---"
        docker exec frr-new vtysh -c "show bgp summary" 2>/dev/null || true
        echo "--- rusty logs ---"
        docker logs rusty 2>&1 | tail -20
    fi
    sleep 1
done

# Allow additional convergence time for route propagation across all 3 hops.
sleep 5

echo ""
echo "--- Test Results ---"

# Test 1: all three sessions established, in particular the two-octet one.
if $GOBGP_OK; then
    pass "gobgp-new <-> rusty eBGP session established (AS4-AS4)"
else
    fail "gobgp-new <-> rusty eBGP session established (AS4-AS4)"
fi

if $BIRD_OK; then
    pass "rusty <-> bird-old eBGP session established despite bird-old lacking the Four-Octet AS Number capability (not refused)"
else
    fail "rusty <-> bird-old eBGP session established despite bird-old lacking the Four-Octet AS Number capability"
fi

if $FRR_OK; then
    pass "bird-old <-> frr-new eBGP session established (AS4-AS4)"
else
    fail "bird-old <-> frr-new eBGP session established (AS4-AS4)"
fi

# Test 2: ENCODE direction. rusty must have downgraded 10.0.1.0/24's AS_PATH to
# two-octet + AS4_PATH; bird-old (real BIRD) must show the reconciled AS_PATH.
ASPATH_1001=$(docker exec bird-old birdc show route all 2>/dev/null \
    | awk '/^10\.0\.1\.0\/24/{f=1; next} f && /BGP.as_path:/{print; exit}' \
    | sed 's/.*BGP.as_path: *//')
if [ "$ASPATH_1001" = "65010 4200000000" ]; then
    pass "bird-old reconstructed AS_PATH '65010 4200000000' for 10.0.1.0/24 from rusty's AS4_PATH"
else
    fail "bird-old AS_PATH for 10.0.1.0/24 is wrong (expected '65010 4200000000', got '$ASPATH_1001')"
    echo "    Debug: bird-old route for 10.0.1.0/24:"
    docker exec bird-old birdc show route all 2>/dev/null || true
fi

# Test 3: no AS4_PATH needed when the whole AS_PATH fits in two octets.
ASPATH_1003=$(docker exec bird-old birdc show route all 2>/dev/null \
    | awk '/^10\.0\.3\.0\/24/{f=1; next} f && /BGP.as_path:/{print; exit}' \
    | sed 's/.*BGP.as_path: *//')
if [ "$ASPATH_1003" = "65010" ]; then
    pass "bird-old shows a clean AS_PATH '65010' for 10.0.3.0/24 (no AS4_PATH needed)"
else
    fail "bird-old AS_PATH for 10.0.3.0/24 is wrong (expected '65010', got '$ASPATH_1003')"
fi

# Test 4: DECODE direction. bird-old must have downgraded 10.0.2.0/24's AS_PATH
# to two-octet + AS4_PATH when relaying to rusty; rusty must reconcile it back.
RUSTY_RIB=$(docker exec rusty gobgp global rib 2>/dev/null || true)
if echo "$RUSTY_RIB" | grep "10.0.2.0/24" | grep -q "65020 4200000001"; then
    pass "rusty reconciled AS_PATH '65020 4200000001' for 10.0.2.0/24 from bird-old's (real BIRD-generated) AS4_PATH"
else
    fail "rusty AS_PATH for 10.0.2.0/24 is wrong (expected to contain '65020 4200000001')"
    echo "    Debug: rusty global RIB:"
    echo "$RUSTY_RIB"
fi

echo ""
echo "--- RIB dumps ---"
echo ""
echo "bird-old RIB:"
docker exec bird-old birdc show route all 2>/dev/null || true
echo ""
echo "rusty RIB:"
echo "$RUSTY_RIB"
echo ""

echo "=== Results: $PASS passed, $FAIL failed ==="

if [ "$FAIL" -gt 0 ]; then
    exit 1
fi
