# Build FRR from source for arm64 support
FROM alpine:latest AS builder

RUN apk add --no-cache \
    alpine-sdk \
    autoconf \
    automake \
    bison \
    c-ares-dev \
    elfutils-dev \
    flex \
    json-c-dev \
    libcap-dev \
    libtool \
    libyang-dev \
    linux-headers \
    pcre2-dev \
    protobuf-c-dev \
    py3-sphinx \
    python3 \
    python3-dev \
    readline-dev

RUN addgroup -S frr && adduser -S -G frr frr && \
    addgroup -S frrvty && adduser frr frrvty

ARG FRR_VERSION=10.2.1
ARG FRR_SHA256=6cbf142d0b12fb8679f5dc95f7638ba6faf848a44f38fd45bf9caeee8c12097c
ADD https://github.com/FRRouting/frr/archive/refs/tags/frr-${FRR_VERSION}.tar.gz /tmp/frr.tar.gz
RUN echo "${FRR_SHA256}  /tmp/frr.tar.gz" | sha256sum -c -
RUN tar xzf /tmp/frr.tar.gz -C /tmp && mv /tmp/frr-frr-${FRR_VERSION} /tmp/frr

WORKDIR /tmp/frr
RUN ./bootstrap.sh && \
    ./configure \
        --prefix=/usr \
        --sysconfdir=/etc/frr \
        --localstatedir=/var/run/frr \
        --sbindir=/usr/lib/frr \
        --enable-user=frr \
        --enable-group=frr \
        --enable-vty-group=frrvty \
        --disable-doc \
        --disable-ldpd \
        --disable-babeld \
        --disable-eigrpd \
        --disable-fabricd \
        --disable-isisd \
        --disable-nhrpd \
        --disable-ospfd \
        --disable-ospf6d \
        --disable-pimd \
        --disable-ripd \
        --disable-ripngd \
        --disable-vrrpd \
        --disable-pathd \
        --disable-pbrd \
        --disable-bfdd \
        --disable-sharpd && \
    make -j$(nproc) && \
    make install DESTDIR=/build

# Runtime
FROM alpine:latest

RUN apk add --no-cache \
    c-ares \
    iproute2 \
    json-c \
    libcap \
    libyang \
    pcre2 \
    protobuf-c \
    readline \
    bash

RUN addgroup -S frr && adduser -S -G frr frr && \
    addgroup -S frrvty && adduser frr frrvty

COPY --from=builder /build/ /

RUN mkdir -p /etc/frr /var/run/frr /var/log/frr && \
    chown -R frr:frr /etc/frr /var/run/frr /var/log/frr

# FRR_CONF_DIR must be passed as a build arg pointing to the test's FRR config
ARG FRR_CONF_DIR
COPY ${FRR_CONF_DIR}/frr.conf /etc/frr/frr.conf
COPY tests/e2e/shared/daemons /etc/frr/daemons
RUN chown -R frr:frr /etc/frr

RUN echo 'service integrated-vtysh-config' > /etc/frr/vtysh.conf && \
    chown frr:frrvty /etc/frr/vtysh.conf

COPY tests/e2e/shared/entrypoint-frr.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
