name: e2e-tracing

on: [pull_request]

jobs:
  e2e-tracing:
    name: Tracing end-to-end
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checking out
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run tracing e2e test
        working-directory: tests/e2e/tracing
        env:
          RUST_TARGET: x86_64-unknown-linux-musl
        run: ./run-test.sh
